services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippetbox
    ports:
    - "5432:5432"
    volumes:
    - snippet_db_data:/var/lib/postgresql/data

volumes:
  snippet_db_data:
